import { SDF_GLSL } from './sdf'

/* ------------------------------------------------------------------ *
 * INNER_SHADOW_MASK_COMPOSITE_FRAGMENT_SHADER — Canvas2D inner shadow
 * mask composite. Samples a blurred ring mask texture generated by
 * Canvas2D (fill → destination-out → blur) and composites onto the
 * scene with SrcOver blend.
 *
 * The mask represents the inner shadow ring: the area of the shape
 * that is NOT covered by the offset shape, blurred. This creates a
 * soft shadow band inside the shape, thicker on the side opposite
 * the offset direction — faithful to InnerShadowModifier.kt.
 *
 * Composite: shadowColor * maskAlpha * shadowAlpha, PREMULTIPLIED SrcOver blend.
 * Output is premultiplied: vec4(color * alpha, alpha). The renderer MUST use
 * blendFunc(ONE, ONE_MINUS_SRC_ALPHA) — premultiplied SrcOver — NOT
 * blendFunc(SRC_ALPHA, ONE_MINUS_SRC_ALPHA) which would square the alpha
 * (making alpha=0.15 contribute only 0.15²=0.0225 — nearly invisible).
 * SDF clip ensures the shadow stays inside the shape boundary
 * (blur that leaked outside is discarded).
 * ------------------------------------------------------------------ */
export const INNER_SHADOW_MASK_COMPOSITE_FRAGMENT_SHADER = /* glsl */ `
precision highp float;

uniform vec2  uCanvasSize;
uniform vec2  uOffset;           // element top-left in canvas px (top-left origin) — SCALED rect
uniform vec2  uSize;             // element size in canvas px — SCALED
uniform vec4  uCornerRadii;      // (topLeft, topRight, bottomRight, bottomLeft) — SCALED
uniform sampler2D uInnerShadowMask; // Canvas2D-generated blurred ring mask
uniform vec2  uMaskOffset;       // margin in device px (for UV mapping: element-local → mask UV)
uniform vec2  uMaskSize;         // total mask size in device px (w+2*margin, h+2*margin)
uniform vec3  uInnerShadowColor; // shadow color RGB
uniform float uInnerShadowAlpha; // shadow alpha
// --- ORIGINAL-SPACE SDF clip (faithful to graphicsLayer { scaleX, scaleY }) ---
uniform vec2  uOriginalSize;        // element size in px (ORIGINAL, unscaled)
uniform float uOriginalCornerRadius; // corner radius in px (ORIGINAL, unscaled)
uniform vec2  uLayerScale;          // (scaleX, scaleY) from graphicsLayer
uniform float uElementRotation;     // rotation in radians (graphicsLayer rotationZ)

${SDF_GLSL}

void main() {
    vec2 screenCoord = vec2(gl_FragCoord.x, uCanvasSize.y - gl_FragCoord.y);

    // Map screen coord → element-local ORIGINAL space (un-scale, un-rotate).
    // The inner shadow mask is drawn in original space (origSize + margin).
    // elementCenter is the same in scaled and original space (scaling is
    // around center).
    vec2 elementCenter = uOffset + uSize * 0.5;
    vec2 centeredScreen = screenCoord - elementCenter;
    vec2 layerScale = max(uLayerScale, vec2(1e-4));
    vec2 centeredOrig = centeredScreen / layerScale;
    vec2 centeredOrigRot = rotateBy(centeredOrig, -uElementRotation);

    // Clip to element shape — hard discard for pixels outside.
    // Faithful to InnerShadowModifier.kt's graphicsLayer clip which applies
    // AFTER BlurMaskFilter: the blurred ring's outward spread is clipped away,
    // but pixels AT the edge (sd ≈ 0) remain at full mask intensity.
    // We use a HARD discard (no smoothstep clipAlpha) because multiplying by
    // clipAlpha at the edge would reduce the inner shadow's peak intensity,
    // creating a visible gap. The mask's own blur softness provides the
    // edge transition, matching the original's clip-after-blur behavior.
    vec2 origHalfSize = uOriginalSize * 0.5;
    float sd = sdShape(centeredOrigRot, origHalfSize, uOriginalCornerRadius);
    if (sd > 0.5) discard;

    // Map to mask UV: original-space coord → mask texture UV.
    // The mask was drawn with translate(margin, margin), so mask (0,0) =
    // element-local (-margin). Element-local coord 0..origSize maps to
    // mask UV (0+margin)/maskSize .. (origSize+margin)/maskSize.
    vec2 maskTexCoord = centeredOrigRot + origHalfSize;  // 0..origSize (element-local)
    vec2 maskUv = (maskTexCoord + uMaskOffset) / uMaskSize;
    if (maskUv.x < 0.0 || maskUv.x > 1.0 || maskUv.y < 0.0 || maskUv.y > 1.0) discard;
    float mask = texture2D(uInnerShadowMask, maskUv).a;
    if (mask < 0.001) discard;

    // Premultiplied SrcOver composite: shadow color × mask × alpha.
    // No clipAlpha multiplier — hard discard at sd>0.5 is sufficient.
    // Output is premultiplied (rgb = color * alpha). Renderer uses
    // gl.blendFunc(ONE, ONE_MINUS_SRC_ALPHA) — premultiplied SrcOver.
    // Do NOT use (SRC_ALPHA, ONE_MINUS_SRC_ALPHA) — that squares the alpha.
    float a = mask * uInnerShadowAlpha;
    gl_FragColor = vec4(uInnerShadowColor * a, a);
}
`
