import { SDF_GLSL } from './sdf'

/* ------------------------------------------------------------------ *
 * INNER_SHADOW_MASK_COMPOSITE_FRAGMENT_SHADER — Canvas2D inner shadow
 * mask composite. Samples a blurred ring mask texture generated by
 * Canvas2D (fill → destination-out → blur) and composites onto the
 * scene with SrcOver blend.
 *
 * The mask represents the inner shadow ring: the area of the shape
 * that is NOT covered by the offset shape, blurred. This creates a
 * soft shadow band inside the shape, thicker on the side opposite
 * the offset direction — faithful to InnerShadowModifier.kt.
 *
 * Composite: shadowColor * maskAlpha * shadowAlpha, PREMULTIPLIED SrcOver blend.
 * Output is premultiplied: vec4(color * alpha, alpha). The renderer MUST use
 * blendFunc(ONE, ONE_MINUS_SRC_ALPHA) — premultiplied SrcOver — NOT
 * blendFunc(SRC_ALPHA, ONE_MINUS_SRC_ALPHA) which would square the alpha
 * (making alpha=0.15 contribute only 0.15²=0.0225 — nearly invisible).
 *
 * Shape clipping: The original Kotlin uses Skia's clipOutline (geometric
 * clip with smooth AA). We replicate this with a SDF smoothstep —
 * NO hard discard. This ensures no visible gaps at the shape boundary
 * and matches the original's smooth clipping behavior exactly.
 * ------------------------------------------------------------------ */
export const INNER_SHADOW_MASK_COMPOSITE_FRAGMENT_SHADER = /* glsl */ `
precision highp float;

uniform vec2  uCanvasSize;
uniform vec2  uOffset;           // element top-left in canvas px (top-left origin) — SCALED rect
uniform vec2  uSize;             // element size in canvas px — SCALED
uniform vec4  uCornerRadii;      // (topLeft, topRight, bottomRight, bottomLeft) — SCALED
uniform sampler2D uInnerShadowMask; // Canvas2D-generated blurred ring mask
uniform vec2  uMaskOffset;       // margin in device px (for UV mapping: element-local → mask UV)
uniform vec2  uMaskSize;         // total mask size in device px (w+2*margin, h+2*margin)
uniform vec3  uInnerShadowColor; // shadow color RGB
uniform float uInnerShadowAlpha; // shadow alpha
// --- ORIGINAL-SPACE SDF clip (faithful to graphicsLayer { scaleX, scaleY }) ---
uniform vec2  uOriginalSize;        // element size in px (ORIGINAL, unscaled)
uniform float uOriginalCornerRadius; // corner radius in px (ORIGINAL, unscaled)
uniform vec2  uLayerScale;          // (scaleX, scaleY) from graphicsLayer
uniform float uElementRotation;     // rotation in radians (graphicsLayer rotationZ)

${SDF_GLSL}

void main() {
    vec2 screenCoord = vec2(gl_FragCoord.x, uCanvasSize.y - gl_FragCoord.y);

    // Map screen coord → element-local ORIGINAL space (un-scale, un-rotate).
    // The inner shadow mask is drawn in original space (origSize + margin).
    // elementCenter is the same in scaled and original space (scaling is
    // around center).
    vec2 elementCenter = uOffset + uSize * 0.5;
    vec2 centeredScreen = screenCoord - elementCenter;
    vec2 layerScale = max(uLayerScale, vec2(1e-4));
    vec2 centeredOrig = centeredScreen / layerScale;
    vec2 centeredOrigRot = rotateBy(centeredOrig, -uElementRotation);

    // SDF for shape clip — faithful to InnerShadowModifier.kt's final
    // clipOutline call before drawLayer. The original uses Skia's
    // geometric clip with smooth AA (sub-pixel transition).
    // We replicate with smoothstep — NO hard discard.
    vec2 origHalfSize = uOriginalSize * 0.5;
    float sd = sdShape(centeredOrigRot, origHalfSize, uOriginalCornerRadius);

    // Smooth clipAlpha: 1.0 fully inside (sd ≤ 0), smoothly fading
    // across the boundary (sd 0→1.5), 0.0 outside (sd ≥ 1.5).
    // The 1.5px transition width matches Skia's clipOutline AA behavior
    // — pixels at the exact boundary (sd=0) retain FULL intensity, with
    // a gentle fade that removes outward blur leakage smoothly.
    // This is NOT a hard discard — it's a smooth clip that matches the
    // original's geometric clipOutline exactly.
    float clipAlpha = 1.0 - smoothstep(0.0, 1.5, sd);

    // Skip truly invisible pixels for performance (not a visual clip)
    if (clipAlpha < 0.004) discard;

    // Map to mask UV: original-space coord → mask texture UV.
    vec2 maskTexCoord = centeredOrigRot + origHalfSize;  // 0..origSize (element-local)
    vec2 maskUv = (maskTexCoord + uMaskOffset) / uMaskSize;

    // Sample the mask texture. CLAMP_TO_EDGE wrapping handles UV values
    // slightly outside (0..1) gracefully — returns transparent at edges.
    float mask = texture2D(uInnerShadowMask, maskUv).a;

    // Skip truly invisible pixels for performance (not a visual clip)
    // Threshold is very low to avoid cutting off faint but visible shadow edges.
    if (mask < 0.003) discard;

    // Premultiplied SrcOver composite: shadowColor × mask × shadowAlpha × clipAlpha.
    // clipAlpha provides smooth shape-boundary transition (faithful to original's
    // clipOutline AA). Output is premultiplied (rgb = color * alpha).
    // Renderer uses gl.blendFunc(ONE, ONE_MINUS_SRC_ALPHA) — premultiplied SrcOver.
    float a = mask * uInnerShadowAlpha * clipAlpha;
    gl_FragColor = vec4(uInnerShadowColor * a, a);
}
`
