package com.kyant.backdrop.catalog;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class drawable {
        public static final int res_0x7f040000_ic_launcher_foreground__0 = 0x7f040000;
        public static final int ic_launcher_background = 0x7f040007;
        public static final int ic_launcher_foreground = 0x7f040008;
    }

    public static final class id {
        public static final int accessibility_action_clickable_span = 0x7f050000;
        public static final int accessibility_custom_action_0 = 0x7f050001;
        public static final int accessibility_custom_action_1 = 0x7f050002;
        public static final int accessibility_custom_action_10 = 0x7f050003;
        public static final int accessibility_custom_action_11 = 0x7f050004;
        public static final int accessibility_custom_action_12 = 0x7f050005;
        public static final int accessibility_custom_action_13 = 0x7f050006;
        public static final int accessibility_custom_action_14 = 0x7f050007;
        public static final int accessibility_custom_action_15 = 0x7f050008;
        public static final int accessibility_custom_action_16 = 0x7f050009;
        public static final int accessibility_custom_action_17 = 0x7f05000a;
        public static final int accessibility_custom_action_18 = 0x7f05000b;
        public static final int accessibility_custom_action_19 = 0x7f05000c;
        public static final int accessibility_custom_action_2 = 0x7f05000d;
        public static final int accessibility_custom_action_20 = 0x7f05000e;
        public static final int accessibility_custom_action_21 = 0x7f05000f;
        public static final int accessibility_custom_action_22 = 0x7f050010;
        public static final int accessibility_custom_action_23 = 0x7f050011;
        public static final int accessibility_custom_action_24 = 0x7f050012;
        public static final int accessibility_custom_action_25 = 0x7f050013;
        public static final int accessibility_custom_action_26 = 0x7f050014;
        public static final int accessibility_custom_action_27 = 0x7f050015;
        public static final int accessibility_custom_action_28 = 0x7f050016;
        public static final int accessibility_custom_action_29 = 0x7f050017;
        public static final int accessibility_custom_action_3 = 0x7f050018;
        public static final int accessibility_custom_action_30 = 0x7f050019;
        public static final int accessibility_custom_action_31 = 0x7f05001a;
        public static final int accessibility_custom_action_4 = 0x7f05001b;
        public static final int accessibility_custom_action_5 = 0x7f05001c;
        public static final int accessibility_custom_action_6 = 0x7f05001d;
        public static final int accessibility_custom_action_7 = 0x7f05001e;
        public static final int accessibility_custom_action_8 = 0x7f05001f;
        public static final int accessibility_custom_action_9 = 0x7f050020;
        public static final int action_container = 0x7f050021;
        public static final int action_divider = 0x7f050022;
        public static final int action_image = 0x7f050023;
        public static final int action_text = 0x7f050024;
        public static final int actions = 0x7f050025;
        public static final int adjacent = 0x7f050026;
        public static final int always = 0x7f050027;
        public static final int alwaysAllow = 0x7f050028;
        public static final int alwaysDisallow = 0x7f050029;
        public static final int androidx_compose_ui_view_compose_view_context = 0x7f05002a;
        public static final int androidx_compose_ui_view_composition_context = 0x7f05002b;
        public static final int androidx_window_activity_scope = 0x7f05002c;
        public static final int async = 0x7f05002d;
        public static final int auto_clear_focus_behavior_tag = 0x7f05002e;
        public static final int blocking = 0x7f05002f;
        public static final int bottomToTop = 0x7f050030;
        public static final int chronometer = 0x7f050031;
        public static final int compose_prefetch_scheduler = 0x7f050032;
        public static final int compose_view_saveable_id_tag = 0x7f050033;
        public static final int consume_window_insets_tag = 0x7f050034;
        public static final int dialog_button = 0x7f050035;
        public static final int draggable = 0x7f050036;
        public static final int edit_text_id = 0x7f050037;
        public static final int fixed = 0x7f050038;
        public static final int forever = 0x7f050039;
        public static final int ghost_view = 0x7f05003a;
        public static final int ghost_view_holder = 0x7f05003b;
        public static final int hide_graphics_layer_in_inspector_tag = 0x7f05003c;
        public static final int hide_ime_id = 0x7f05003d;
        public static final int hide_in_inspector_tag = 0x7f05003e;
        public static final int icon = 0x7f05003f;
        public static final int icon_group = 0x7f050040;
        public static final int info = 0x7f050041;
        public static final int inspection_slot_table_set = 0x7f050042;
        public static final int is_pooling_container_tag = 0x7f050043;
        public static final int italic = 0x7f050044;
        public static final int jumpCut = 0x7f050045;
        public static final int line1 = 0x7f050046;
        public static final int line3 = 0x7f050047;
        public static final int locale = 0x7f050048;
        public static final int ltr = 0x7f050049;
        public static final int never = 0x7f05004a;
        public static final int normal = 0x7f05004b;
        public static final int notification_background = 0x7f05004c;
        public static final int notification_main_column = 0x7f05004d;
        public static final int notification_main_column_container = 0x7f05004e;
        public static final int parent_matrix = 0x7f05004f;
        public static final int pooling_container_listener_holder_tag = 0x7f050050;
        public static final int report_drawn = 0x7f050051;
        public static final int right_icon = 0x7f050052;
        public static final int right_side = 0x7f050053;
        public static final int rtl = 0x7f050054;
        public static final int save_non_transition_alpha = 0x7f050055;
        public static final int save_overlay_view = 0x7f050056;
        public static final int systemDefault = 0x7f050057;
        public static final int tag_accessibility_actions = 0x7f050058;
        public static final int tag_accessibility_clickable_spans = 0x7f050059;
        public static final int tag_accessibility_heading = 0x7f05005a;
        public static final int tag_accessibility_pane_title = 0x7f05005b;
        public static final int tag_compat_insets_dispatch = 0x7f05005c;
        public static final int tag_on_apply_window_listener = 0x7f05005d;
        public static final int tag_on_receive_content_listener = 0x7f05005e;
        public static final int tag_on_receive_content_mime_types = 0x7f05005f;
        public static final int tag_screen_reader_focusable = 0x7f050060;
        public static final int tag_state_description = 0x7f050061;
        public static final int tag_system_bar_state_monitor = 0x7f050062;
        public static final int tag_transition_group = 0x7f050063;
        public static final int tag_unhandled_key_event_manager = 0x7f050064;
        public static final int tag_unhandled_key_listeners = 0x7f050065;
        public static final int tag_window_insets_animation_callback = 0x7f050066;
        public static final int text = 0x7f050067;
        public static final int text2 = 0x7f050068;
        public static final int time = 0x7f050069;
        public static final int title = 0x7f05006a;
        public static final int topToBottom = 0x7f05006b;
        public static final int transition_clip = 0x7f05006c;
        public static final int transition_current_scene = 0x7f05006d;
        public static final int transition_image_transform = 0x7f05006e;
        public static final int transition_layout_save = 0x7f05006f;
        public static final int transition_pause_alpha = 0x7f050070;
        public static final int transition_position = 0x7f050071;
        public static final int transition_scene_layoutid_cache = 0x7f050072;
        public static final int transition_transform = 0x7f050073;
        public static final int view_tree_disjoint_parent = 0x7f050074;
        public static final int view_tree_lifecycle_owner = 0x7f050075;
        public static final int view_tree_navigation_event_dispatcher_owner = 0x7f050076;
        public static final int view_tree_on_back_pressed_dispatcher_owner = 0x7f050077;
        public static final int view_tree_saved_state_registry_owner = 0x7f050078;
        public static final int view_tree_view_model_store_owner = 0x7f050079;
        public static final int wrapped_composition_tag = 0x7f05007a;
    }

    public static final class mipmap {
        public static final int ic_launcher = 0x7f080000;
        public static final int ic_launcher_round = 0x7f080001;
    }

    public static final class string {
        public static final int androidx_startup = 0x7f090002;
        public static final int app_name = 0x7f090003;
        public static final int in_progress = 0x7f090010;
        public static final int indeterminate = 0x7f090011;
        public static final int not_selected = 0x7f090013;
        public static final int selected = 0x7f090016;
        public static final int state_empty = 0x7f090018;
        public static final int state_off = 0x7f090019;
        public static final int state_on = 0x7f09001a;
        public static final int switch_role = 0x7f09001c;
        public static final int tab = 0x7f09001d;
        public static final int template_percent = 0x7f09001e;
    }

    public static final class style {
        public static final int Theme_Catalog = 0x7f0a0007;
    }
}
